export const initialUsers = [
  {
    id: "EMP001",
    name: "Demo Employee",
    email: "demo@dayflow.com",
    password: "demo123",
    role: "employee",
    department: "Engineering",
    designation: "Software Developer",
    status: "Active",
    phone: "9876543210",
    address: "Bangalore, Karnataka",
    salary: {
      base: 50000,
      allowances: 10000,
      deductions: 3000,
    },
    jobDetails: {
      joiningDate: "2025-01-10",
      employmentType: "Full Time",
      manager: "HR Manager",
    },
    documents: ["Aadhaar Card", "PAN Card", "Offer Letter"],
    profilePicture: "",
    verified: true,
  },
  {
    id: "EMP002",
    name: "Rahul Kumar",
    email: "rahul@dayflow.com",
    password: "rahul123",
    role: "employee",
    department: "Finance",
    designation: "Accountant",
    status: "Active",
    phone: "9876501234",
    address: "Chennai, Tamil Nadu",
    salary: {
      base: 45000,
      allowances: 8000,
      deductions: 2500,
    },
    jobDetails: {
      joiningDate: "2024-08-12",
      employmentType: "Full Time",
      manager: "Finance Manager",
    },
    documents: ["Aadhaar Card", "PAN Card"],
    profilePicture: "",
    verified: true,
  },
  {
    id: "EMP003",
    name: "Priya Sharma",
    email: "priya@dayflow.com",
    password: "priya123",
    role: "employee",
    department: "Human Resources",
    designation: "HR Executive",
    status: "Active",
    phone: "9876123456",
    address: "Hyderabad, Telangana",
    salary: {
      base: 48000,
      allowances: 9000,
      deductions: 2800,
    },
    jobDetails: {
      joiningDate: "2025-03-01",
      employmentType: "Full Time",
      manager: "HR Manager",
    },
    documents: ["Aadhaar Card", "PAN Card", "Offer Letter"],
    profilePicture: "",
    verified: true,
  },
];

export const initialAdmins = [
  {
    id: "ADM001",
    name: "Admin User",
    email: "admin@dayflow.com",
    password: "admin123",
    role: "admin",
    department: "Human Resources",
    designation: "HR Manager",
    status: "Active",
    phone: "9999999999",
    address: "Bangalore, Karnataka",
    salary: {
      base: 80000,
      allowances: 15000,
      deductions: 5000,
    },
    jobDetails: {
      joiningDate: "2023-01-01",
      employmentType: "Full Time",
      manager: "Management",
    },
    documents: ["Aadhaar Card", "PAN Card"],
    profilePicture: "",
    verified: true,
  },
];

export const initialAttendance = [
  {
    id: 1,
    employeeId: "EMP001",
    date: "2026-08-22",
    checkIn: "09:00 AM",
    checkOut: "06:00 PM",
    totalHours: "08:00",
    status: "Present",
  },
  {
    id: 2,
    employeeId: "EMP001",
    date: "2026-08-21",
    checkIn: "09:05 AM",
    checkOut: "06:02 PM",
    totalHours: "07:57",
    status: "Present",
  },
  {
    id: 3,
    employeeId: "EMP001",
    date: "2026-08-20",
    checkIn: "09:15 AM",
    checkOut: "06:00 PM",
    totalHours: "07:45",
    status: "Present",
  },
  {
    id: 4,
    employeeId: "EMP001",
    date: "2026-08-19",
    checkIn: "-",
    checkOut: "-",
    totalHours: "-",
    status: "Leave",
  },
  {
    id: 5,
    employeeId: "EMP002",
    date: "2026-08-22",
    checkIn: "09:10 AM",
    checkOut: "06:00 PM",
    totalHours: "07:50",
    status: "Present",
  },
  {
    id: 6,
    employeeId: "EMP003",
    date: "2026-08-22",
    checkIn: "-",
    checkOut: "-",
    totalHours: "-",
    status: "Absent",
  },
];

export const initialLeaveRequests = [
  {
    id: "LR001",
    employeeId: "EMP001",
    employeeName: "Demo Employee",
    type: "Sick",
    startDate: "2026-08-25",
    endDate: "2026-08-26",
    remarks: "Medical appointment",
    status: "Pending",
    hrComment: "",
  },
  {
    id: "LR002",
    employeeId: "EMP002",
    employeeName: "Rahul Kumar",
    type: "Paid",
    startDate: "2026-08-28",
    endDate: "2026-08-29",
    remarks: "Personal work",
    status: "Approved",
    hrComment: "Approved by HR",
  },
];

export const initialPayroll = [
  {
    employeeId: "EMP001",
    base: 50000,
    allowances: 10000,
    deductions: 3000,
  },
  {
    employeeId: "EMP002",
    base: 45000,
    allowances: 8000,
    deductions: 2500,
  },
  {
    employeeId: "EMP003",
    base: 48000,
    allowances: 9000,
    deductions: 2800,
  },
];

export const initialActivities = [
  {
    id: 1,
    employeeId: "EMP001",
    title: "Attendance marked",
    description: "Today at 09:00 AM",
  },
  {
    id: 2,
    employeeId: "EMP001",
    title: "Leave request submitted",
    description: "Today at 10:30 AM",
  },
];